### ISSUE TITLE
overlay2-fs driver not working properly on Debian 10

### ISSUE THREAD

**Issue by maximumG** [rootless-containers/rootlesskit#154]
We are using Debian 10 Buster with kernel 4.19. As stated in [the documentation](https://docs.docker.com/engine/security/rootless/#distribution-specific-hint) this kernel allows to mount overlayfs in user namespace as non-root user.

Unfortunately when the docker daemon is started as rootless with overlay2 driver we are not able to pull any image from dockerhub and end up with the message described below. **However** the old overlay driver is working as expected.

Do you have any clue on this issue ? Has anyone encountered the same problem ?

### Command to start docker as rootless with overlay2-fs

```
/home/testuser/bin/dockerd-rootless.sh --experimental --storage-driver=overlay2 --bip=100.64.1.0/16
```

### Error when trying to pull an image

```bash
docker pull jboss/keycloak

Using default tag: latest
latest: Pulling from jboss/keycloak
600f7e2abab1: Pull complete 
6cd4d9d86398: Extracting  1.653kB/1.653kB
5402af5581b0: Download complete 
b91909199448: Download complete 
6ae51cb1a0de: Download complete 
failed to register layer: Error processing tar file(exit status 1): replaceDirWithOverlayOpaque("/root/buildinfo") failed: createDirWithOverlayOpaque("/root/rdwoo893274543") failed: failed to mkdir /root/rdwoo893274543/m/d: mkdir /root/rdwoo893274543/m/d: input/output error
```

When we use the old driver `overlay`, the pull is sucessfull, see below.

 ### Command to start docker as rootless with overlay-fs

```
/home/testuser/bin/dockerd-rootless.sh --experimental --storage-driver=overlay --bip=100.64.1.0/16
```

### Success when trying to pull an image

```bash
docker pull jboss/keycloak

Using default tag: latest
latest: Pulling from jboss/keycloak
600f7e2abab1: Pull complete 
6cd4d9d86398: Pull complete 
5402af5581b0: Pull complete 
b91909199448: Pull complete 
6ae51cb1a0de: Pull complete 
Digest: sha256:e9248bcf1d1444ab6d652e2302ef906321b9107b1a4d324aef2ab9479e6f2322
Status: Downloaded newer image for jboss/keycloak:latest
docker.io/jboss/keycloak:latest
```

As a side note here are the content of our sysctl.conf et modprobe.conf

/etc/sysctl.d/50-docker.conf
```
net.ipv4.ip_unprivileged_port_start=0
net.ipv4.ping_group_range = 0 2147483647
kernel.unprivileged_userns_clone=1
```

/etc/modprobe.d/overlay2.conf
```
options overlay permit_mounts_in_userns=1
```

**Comment by AkihiroSuda** [comment]
Seems https://github.com/docker/for-linux/issues/1055

The issue seems on the kernel
