### ISSUE TITLE
[rootlesskit:parent] error: failed to start the child: fork/exec /proc/self/exe: operation not permitted

### ISSUE THREAD

**Issue by Masber** [rootless-containers/rootlesskit#172]
Hi,

I am new to docker/container world and I am trying to build an image inside a container using buildkit as a non-root user.
I have downloaded rootlesskit and buildkit but for some reason I can't make buildkit to run as a non-root user
My distro is debian 9

```
jenkins@407b28127b28:/tmp$ cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
jenkins@407b28127b28:/tmp$ cat /proc/sys/kernel/unprivileged_userns_clone
1
jenkins@407b28127b28:/tmp$ id -u
1000
jenkins@407b28127b28:/tmp$ whoami
jenkins
jenkins@407b28127b28:/tmp$ grep "^$(whoami):" /etc/subuid
jenkins:100000:65536
jenkins@407b28127b28:/tmp$ grep "^$(whoami):" /etc/subgid
jenkins:100000:65536
jenkins@407b28127b28:/tmp$ newuidmap
usage: newuidmap <pid> <uid> <loweruid> <count> [ <uid> <loweruid> <count> ] ... 
jenkins@407b28127b28:/tmp$ newgidmap
usage: newgidmap <pid> <gid> <lowergid> <count> [ <gid> <lowergid> <count> ] ... 
jenkins@407b28127b28:/tmp$ ./rootlesskit bin/buildkitd 
[rootlesskit:parent] error: failed to start the child: fork/exec /proc/self/exe: operation not permitted
jenkins@407b28127b28:/tmp$ ./rootlesskit bash
[rootlesskit:parent] error: failed to start the child: fork/exec /proc/self/exe: operation not permitted
```
I hope I am doing things right, Any thoughts?

**Comment by AkihiroSuda** [comment]
If you are trying to run RootlessKit inside a Docker container, you need to run the container with `docker run --security-opt seccomp=unconfined --security-opt apparmor=unconfined`

https://github.com/moby/buildkit/blob/master/docs/rootless.md#docker

**Comment by Masber** [comment]
sorry, forgot to mention that the container engine is containerd managed by k8s, does it change your proposal?

**Comment by AkihiroSuda** [comment]
Should set Pod annotations like this
```yaml
  annotations:
    container.apparmor.security.beta.kubernetes.io/buildkitd: unconfined
    container.seccomp.security.alpha.kubernetes.io/buildkitd: unconfined
```

https://github.com/moby/buildkit/blob/477b1aab89dae85d31a48797f341d6bd7527fa5a/examples/kubernetes/deployment%2Bservice.rootless.yaml#L16-L18

**Comment by AkihiroSuda** [comment]
Is this issue closable?

**Comment by cyxinda** [comment]
run `echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns ` then 'reboot` system.
ubuntu24.04's apparmor would forbid the rootless.

**Comment by munishchouhan** [comment]
I am using `--privileged`, but still getting error in mac
```
could not connect to unix:///run/user/1000/buildkit/buildkitd.sock after 10 trials
========== log ==========
[rootlesskit:parent] error: failed to start the child: fork/exec /proc/self/exe: invalid argument
sh: can't kill pid 14: No such process
```

**Comment by Lewiscowles1986** [comment]
I'm getting this on a mac even after following

https://docs.docker.com/reference/cli/docker/buildx/build/#allow

it's a little frustrating. I'm guessing as the last comment was about a mac, this could be that the VM docker desktop is using has a security setting which is enforcing this outside of the container environment?

**Comment by munishchouhan** [comment]
Try providing the platform as ARM64

**Comment by Lewiscowles1986** [comment]
so it turned out, I needed to separately run --force after downloading on an executable rootless installer. I'd actually used a github actions runner project to base the install from... theirs must be broken as even when I downloaded it, it didn't build, with this error.

It's not fully worked as docker doesn't have enough to use rslave on root. Apparently I need to change some filesystem drivers to use on mac with Docker Desktop 🤷

**Comment by puckettgw** [comment]
> run `echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns ` then 'reboot` system. ubuntu24.04's apparmor would forbid the rootless.

Editing the proc entry and then rebooting would have zero effect... /proc is volatile
