### ISSUE TITLE
Default path of StateDir should be locked for preventing automatic clean-up by systemd-tmpfiles.

### ISSUE THREAD

**Issue by haruo31** [rootless-containers/rootlesskit#185]
rootlesskit creates `/tmp/rootlesskitXXXX` directory if rootlesskit is launched without `--state-dir` option. But files in StateDir have no protection for automatic cleanup from systemd-tmpfiles. It could be lost `*.sock` files unexpectedly.

the systemd documentation describes how to protect files from automatic clean-up. (I suppose the number 3 is suitable for rootlesskit.)
https://systemd.io/TEMPORARY_DIRECTORIES/

**Comment by AkihiroSuda** [comment]
Thank you for reporting. The number 3 SGTM. Would you be interested in opening a PR?

**Comment by AkihiroSuda** [comment]
Fixed in #188, thanks @HappyTobi
