### ISSUE TITLE
Possibility to connect to a VPN for the network NS created by rootlesskit

### ISSUE THREAD

**Issue by frezbo** [rootless-containers/rootlesskit#19]
I would like to have per process VPN available. Is it possible from `rootlesskit` to connect to a VPN and have it available in the process spawned by rootlesskit. Is it as simple as connecting to the VPN inside the shell created by rootlesskit

**Comment by AkihiroSuda** [comment]
You should be able to do `ip netns ...` and almost whatever inside `rootlesskit --net=slirp4netns --copy-up=/etc --copy-up=/run`.

Let me know if it does not work for you.

**Comment by frezbo** [comment]
I will have to spend some time on this and want to see if https://github.com/pekman/openvpn-netns can be run inside `rootlesskit`

**Comment by AkihiroSuda** [comment]
did it work for you?
@frezbo

**Comment by AkihiroSuda** [comment]
I'm closing this issue, but feel free to ping me to reopen
