### ISSUE TITLE
How to run a process within rootlesskit as a non-root user?

### ISSUE THREAD

**Issue by denisvmedia** [rootless-containers/rootlesskit#208]
Here is basically, what I'm trying to do:

```
fab@wp:~/html$ rootlesskit bash
root@wp:~/html# id
uid=0(root) gid=0(root) groups=0(root)
root@wp:~/html# id www-data
uid=33(www-data) gid=33(www-data) groups=33(www-data)
root@wp:~/html# sudo -u www-data ls
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
root@wp:~/html# su www-data -s /bin/bash
su: Authentication failure
```

I.e. I'm switching to `rootlesskit` and then trying to run some process as a subuser. But I seem to not able to do that. Is it actually possible?

**Comment by AkihiroSuda** [comment]
You need to have `/etc/subuid` and `/etc/subgid`

**Comment by denisvmedia** [comment]
Of course, I do have them.

**Comment by denisvmedia** [comment]
cat /etc/subuid
fab:165536:65536
root@wp:/etc# cat /etc/subgid
fab:165536:65536

**Comment by AkihiroSuda** [comment]
This seems to work
```
$ rootlesskit runuser -u www-data id
uid=33(www-data) gid=33(www-data) groups=33(www-data)
```

I guess su and sudo do not work because they probably attempt to dome PAM stuff with the host.

**Comment by denisvmedia** [comment]
That's right, it works! Thank you.
