### ISSUE TITLE
rootless kit exit with error

### ISSUE THREAD

**Issue by mklnu** [rootless-containers/rootlesskit#229]
When run rootless kit in embedded board, roolesskit exit with error.

Hardware info:

Processor:
SAMA5D36 (324-ball BGA package) ARM Cortex-A5 Processor with ARM 
v7-A Thumb2® instruction set, core frequency up to 536 MHz.

Eval board:
https://www.microchip.com/DevelopmentTools/ProductDetails/PartNO/ATSAMA5D3-XPLD

embedded linux:
$ uname -a
Linux buildroot 5.5.6 #1  armv7l GNU/Linux        (Busybox)

rootless kit is built from source in buildroot.

Docker (regular docker run in root) 20.10 runs OK on the board. 
However when run rootless mode (Docker 20.10 release), rootless kit exit with error.

If you need more info, please let me know.

Thanks!

========= debug info ==============

$ rootlesskit --debug bash
[rootlesskit:parent] error: exit status 1
newuidmap 362 [0 1003 1 1 100000 65536 65537 100000 65536] failed: newuidmap: write to uid_map failed: Invalid argument

github.com/rootless-containers/rootlesskit/pkg/parent.setupUIDGIDMap
	github.com/rootless-containers/rootlesskit/pkg/parent/parent.go:289
github.com/rootless-containers/rootlesskit/pkg/parent.Parent
	github.com/rootless-containers/rootlesskit/pkg/parent/parent.go:133
main.main.func2
	github.com/rootless-containers/rootlesskit/cmd/rootlesskit/main.go:173
github.com/urfave/cli/v2.(*App).RunContext
	github.com/urfave/cli/v2@v2.2.0/app.go:315
github.com/urfave/cli/v2.(*App).Run
	github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main
	github.com/rootless-containers/rootlesskit/cmd/rootlesskit/main.go:175
runtime.main
	runtime/proc.go:204
runtime.goexit
	runtime/asm_arm.s:857
failed to setup UID/GID map
github.com/rootless-containers/rootlesskit/pkg/parent.Parent
	github.com/rootless-containers/rootlesskit/pkg/parent/parent.go:134
main.main.func2
	github.com/rootless-containers/rootlesskit/cmd/rootlesskit/main.go:173
github.com/urfave/cli/v2.(*App).RunContext
	github.com/urfave/cli/v2@v2.2.0/app.go:315
github.com/urfave/cli/v2.(*App).Run
	github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main
	github.com/rootless-containers/rootlesskit/cmd/rootlesskit/main.go:175
runtime.main
	runtime/proc.go:204
runtime.goexit
	runtime/asm_arm.s:857
$

**Comment by AkihiroSuda** [comment]
Does `unshare -r` work? If not, probably your kernel is not compiled with userNS support.

Also please see https://rootlesscontaine.rs/getting-started/common/sysctl/

**Comment by mklnu** [comment]
Mr. Akihiro Suda,

The rootless docker is great and thank you so much for your contribution to the project. Your information is very valuable. Please keep this open temporary and I will give my updated info later (I am in the middle of debugging).

Thanks again for your quick response and very helpful information!

**Comment by mklnu** [comment]
Hi Mr.  Akihiro Suda,

Thanks for your info. I double checked the kernel config and it has userns support. However user space packages were missing and I have fixed several packages (all packages added and compiled from source for our embedded linux system).  Now I can run "unshare -r" and "rootlesskit sh". However I still get other errors when run dockerd-rootless.sh. Please refer to the following info.

Info : I can run "mount rslave"  and "ip tuntap add name tap0 mode tap" as root but donot know how to debug it in rootlesskit.

Is there any linux command steps I can follow to debug this? So I may better understand and isolate where it fails. e.g. like last time you ask if I can run "unshare -r" which give me very good direction to debug.

Thank you so much!!!



1.)  <------ OK
$ unshare -r
# exit

2.) <------ OK
$ rootlesskit sh
$ whoami
root

3.) <------ INFO
$ env
USER=testMAIL=/var/mail/test
HOME=/home/test
PATH=/home/test/bin:/bin:/sbin:/usr/bin:/usr/sbin
XDG_RUNTIME_DIR=/home/test/.docker/run
SHELL=/bin/sh
DOCKER_HOST=unix:///home/test/.docker/run/docker.sock

4.)  dockerd-rootless.sh  <------ WARNING + FAILED

(((>>>>>>>>>>>WARN[0000] The host root filesystem is mounted as "". Setting child propagation to "rslave" is not supported. 
>>>>>>>>>>>open: Permission denied
>>>>>>>>>>.[rootlesskit:parent] error: failed to setup network &{logWriter:0x810f28 binary:slirp4netns mtu:65520 ipnet:<nil> ))))

+ '[' -w /home/test/.docker/run ]
+ '[' -w /home/test ]
+ rootlesskit=
+ which docker-rootlesskit
+ which rootlesskit
+ rootlesskit=rootlesskit
+ break
+ '[' -z rootlesskit ]
+ : 
+ : 
+ : builtin
+ : auto
+ : auto
+ net=
+ mtu=
+ '[' -z ]
+ which slirp4netns
+ grep -qw -- --netns-type
+ slirp4netns --help
+ net=slirp4netns
+ '[' -z ]
+ mtu=65520
+ '[' -z slirp4netns ]
+ '[' -z 65520 ]
+ '[' -z ]
+ _DOCKERD_ROOTLESS_CHILD=1
+ export _DOCKERD_ROOTLESS_CHILD
+ exec rootlesskit '--net=slirp4netns' '--mtu=65520' '--slirp4netns-sandbox=auto' '--slirp4netns-seccomp=auto' --disable-host-loopback '--port-driver=builtin' '--copy-up=/etc' '--copy-up=/run' '--propagation=rslave' /home/test/bin/dockerd-rootless.sh
WARN[0000] The host root filesystem is mounted as "". Setting child propagation to "rslave" is not supported. 
open: Permission denied
[rootlesskit:parent] error: failed to setup network &{logWriter:0x810f28 binary:slirp4netns mtu:65520 ipnet:<nil> disableHostLoopback:true apiSocketPath: enableSandbox:true enableSeccomp:true}: setting up tap tap0: executing [[nsenter -t 594 -n -m -U --preserve-credentials ip tuntap add name tap0 mode tap] [nsenter -t 594 -n -m -U --preserve-credentials ip link set tap0 up]]: exit status 1
$ [rootlesskit:child ] error: parsing message from fd 3: EOF




5.)  debug-dockerd-rootless.sh <------ DEBUG INFO : WARNING AND ERROR


+ '[' -w /home/test/.docker/run ]
+ '[' -w /home/test ]
+ rootlesskit=
+ which docker-rootlesskit
+ which rootlesskit
+ rootlesskit=rootlesskit
+ break
+ '[' -z rootlesskit ]
+ : 
+ : 
+ : builtin
+ : auto
+ : auto
+ net=
+ mtu=
+ '[' -z ]
+ which slirp4netns
+ grep -qw -- --netns-type
+ slirp4netns --help
+ net=slirp4netns
+ '[' -z ]
+ mtu=65520
+ '[' -z slirp4netns ]
+ '[' -z 65520 ]
+ '[' -z ]
+ _DOCKERD_ROOTLESS_CHILD=1
+ export _DOCKERD_ROOTLESS_CHILD
+ exec rootlesskit --debug '--net=slirp4netns' '--mtu=65520' '--slirp4netns-sandbox=auto' '--slirp4netns-seccomp=auto' --disable-host-loopback '--port-driver=builtin' '--copy-up=/etc' '--copy-up=/run' '--propagation=rslave' /home/test/bin/debug-dockerd-rootless.sh
DEBU[0000] slirp4netns features &{SupportsCIDR:true SupportsDisableHostLoopback:true SupportsAPISocket:true SupportsEnableSandbox:true SupportsEnableSeccomp:true KernelSupportsEnableSeccomp:true} 
WARN[0000] The host root filesystem is mounted as "". Setting child propagation to "rslave" is not supported. 
DEBU[0000] executing [nsenter -t 621 -n -m -U --preserve-credentials ip tuntap add name tap0 mode tap] 
DEBU[0000] child: got msg from parent: {Stage:0 Message0:{} Message1:{StateDir: Network:{Dev: IP: Netmask:0 Gateway: DNS: MTU:0 Opaque:map[]} Port:{Opaque:map[]}}} 
open: Permission denied
[rootlesskit:parent] error: exit status 1
executing [[nsenter -t 621 -n -m -U --preserve-credentials ip tuntap add name tap0 mode tap] [nsenter -t 621 -n -m -U --preserve-credentials ip link set tap0 up]]
github.com/rootless-containers/rootlesskit/pkg/network/parentutils.PrepareTap
	github.com/rootless-containers/rootlesskit/pkg/network/parentutils/parentutils.go:17
github.com/rootless-containers/rootlesskit/pkg/network/slirp4netns.(*parentDriver).ConfigureNetwork
	github.com/rootless-containers/rootlesskit/pkg/network/slirp4netns/slirp4netns.go:141
github.com/rootless-containers/rootlesskit/pkg/parent.Parent
	github.com/rootless-containers/rootlesskit/pkg/parent/parent.go:156
main.main.func2
	github.com/rootless-containers/rootlesskit/cmd/rootlesskit/main.go:173
github.com/urfave/cli/v2.(*App).RunContext
	github.com/urfave/cli/v2@v2.2.0/app.go:315
github.com/urfave/cli/v2.(*App).Run
	github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main
	github.com/rootless-containers/rootlesskit/cmd/rootlesskit/main.go:175
runtime.main
	runtime/proc.go:204
runtime.goexit
	runtime/asm_arm.s:857
setting up tap tap0
github.com/rootless-containers/rootlesskit/pkg/network/slirp4netns.(*parentDriver).ConfigureNetwork
	github.com/rootless-containers/rootlesskit/pkg/network/slirp4netns/slirp4netns.go:142
github.com/rootless-containers/rootlesskit/pkg/parent.Parent
	github.com/rootless-containers/rootlesskit/pkg/parent/parent.go:156
main.main.func2
	github.com/rootless-containers/rootlesskit/cmd/rootlesskit/main.go:173
github.com/urfave/cli/v2.(*App).RunContext
	github.com/urfave/cli/v2@v2.2.0/app.go:315
github.com/urfave/cli/v2.(*App).Run
	github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main
	github.com/rootless-containers/rootlesskit/cmd/rootlesskit/main.go:175
runtime.main
	runtime/proc.go:204
runtime.goexit
	runtime/asm_arm.s:857
failed to setup network &{logWriter:0x810f40 binary:slirp4netns mtu:65520 ipnet:<nil> disableHostLoopback:true apiSocketPath: enableSandbox:true enableSeccomp:true}
github.com/rootless-containers/rootlesskit/pkg/parent.Parent
	github.com/rootless-containers/rootlesskit/pkg/parent/parent.go:161
main.main.func2
	github.com/rootless-containers/rootlesskit/cmd/rootlesskit/main.go:173
github.com/urfave/cli/v2.(*App).RunContext
	github.com/urfave/cli/v2@v2.2.0/app.go:315
github.com/urfave/cli/v2.(*App).Run
	github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main
	github.com/rootless-containers/rootlesskit/cmd/rootlesskit/main.go:175
runtime.main
	runtime/proc.go:204
runtime.goexit
	runtime/asm_arm.s:857
$ [rootlesskit:child ] error: EOF
parsing message from fd 3
github.com/rootless-containers/rootlesskit/pkg/child.Child
	github.com/rootless-containers/rootlesskit/pkg/child/child.go:200
main.main.func2
	github.com/rootless-containers/rootlesskit/cmd/rootlesskit/main.go:166
github.com/urfave/cli/v2.(*App).RunContext
	github.com/urfave/cli/v2@v2.2.0/app.go:315
github.com/urfave/cli/v2.(*App).Run
	github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main
	github.com/rootless-containers/rootlesskit/cmd/rootlesskit/main.go:175
runtime.main
	runtime/proc.go:204
runtime.goexit
	runtime/asm_arm.s:857

**Comment by AkihiroSuda** [comment]
Please make sure /dev/net/tun is writable

**Comment by mklnu** [comment]
Hi Mr. Akihiro Suda,

With your helps, the docker rootless is working on the embedded linux. Thanks and respect to you for your kindness, great helps and the great project!
