### ISSUE TITLE
No IPv6 with slirp4netns

### ISSUE THREAD

**Issue by gnat** [rootless-containers/rootlesskit#258]
IPv6 works fine with the default port driver, but the moment I set `DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER="slirp4netns"` I can no longer use IPv6. 

IPv4 works as intended.

slirp4netns is necessary in order to get the end-users source IP.

Any insight? Using Rootless Docker 20.10.7

**Comment by AkihiroSuda** [comment]
Slirp4netns still does not support v6 forwarding https://github.com/rootless-containers/slirp4netns/issues/253
