### ISSUE TITLE
builtin portdriver does not propagate source IP adresses

### ISSUE THREAD

**Issue by Gymnae** [rootless-containers/rootlesskit#281]
I'd like to lower the overhead of slirp4netns for both net and port driver, but it seems I can't just switch to lxc-user-nic for net and keep port driver as slirp4netns, because this combination appears unsupported.

Using lxc-user-nic for net and builtin for port driver does not propagate the source IP addresses, which makes it not usable for many web services which need to know the origin IP.

Is it possible to propagate source IPs via the buildin port driver?

**Comment by AkihiroSuda** [comment]
Known limitation.
I’m not sure how we could propagate src IP.

**Comment by Gymnae** [comment]
Understood.
Is there a way to combine net lxc-user-nic with slirp4netns as port driver? My attempts failed. The system unit did not want to start

**Comment by AkihiroSuda** [comment]
> Is there a way to combine net lxc-user-nic with slirp4netns as port driver?

Not possible.
