### ISSUE TITLE
Consider moving from 10.0.2.0/24 to a /24 in 100.64.0.0/10 

### ISSUE THREAD

**Issue by storrgie** [rootless-containers/rootlesskit#283]
Ran into a conflict where the hardcoded 10.0.2.0/24 is in conflict with a deployment.

Would it be possible to consider using something that _isn't_ in the [RFC1918 space](https://en.wikipedia.org/wiki/Private_network#Private_IPv4_address_spaces) and instead use the [reserved ipv4 CGNAT space of 100.64.0.0/10, or even just /24](https://en.wikipedia.org/wiki/Reserved_IP_addresses).

It is _entirely likely_ that someone else either has run into this, or will run into it in the future as 10.0.2.0/24 is extremely likely to be used by large deployments or large institutions. Where as 100.64.0.0/10 is far less likely to be commonly seen, and is reserved to be a "carrier" type subnet for internal networking... much the same purpose as what is being done in this project.

**Comment by jmpolom** [comment]
This seems like a pretty reasonable suggestion. At a minimum, if using the CGNAT space isn't possible, a more randomized choice from the 10.0.0.0/8 space should be made. The likelihood of a conflict with 10.0.2.0/24 seems nearly a certainty since large organizations frequently adopt the 10.0.0.0/8 space for campus networks, and often start from the lower end.

**Comment by AkihiroSuda** [comment]
I don't think we can change the default, as it will break existing environments, but you can specify a custom CIDR:
```
rootlesskit --cidr=192.168.123.0/24 ...
```

If you are using Rootless Docker, the `--cidr=...` flags can be specified like this:
```
$ cat <<EOF >~/.config/systemd/user/docker.service.d/override.conf
[Service]
Environment="DOCKERD_ROOTLESS_ROOTLESSKIT_FLAGS=--cidr=192.168.123.0/24"
EOF

$ systemctl --user daemon-reload 
$ systemctl --user restart docker
```

**Comment by AkihiroSuda** [comment]
Let me close this, as we can’t change the default but the users can specify custom CIDR
