### ISSUE TITLE
[Docker] How to use remote API with rootless kit and non-root user

### ISSUE THREAD

**Issue by flaiming** [rootless-containers/rootlesskit#287]
Hi, I have a problem with using docker remote API with rootless kit. 
I have a virtual server in Azure running Debian 11 and docker CE with installed rootless kit.
Remote API is enabled by this tutorial https://medium.com/@ssmak/how-to-enable-docker-remote-api-on-docker-host-7b73bd3278c6
I will run for example hello-world instance by running `docker run hello-world`. Now `docker ps` will show me 1 running container.

On another server I will run
`curl -s -XGET "http://meeseeks:2375/containers/json?all=true"`
This will get me `[]` instead of expected list with running hello-world container info.

I figured out that when I will run hello-world container as root `sudo docker run hello-world`, it works as expected and I will get list with this running container by remote API.

**My question is - how to access non-root docker with remote API?**

**Comment by AkihiroSuda** [comment]
> Remote API is enabled by this tutorial https://medium.com/@ssmak/how-to-enable-docker-remote-api-on-docker-host-7b73bd3278c6

This tutorial isn't right.
Exposing tcp://0.0.0.0:2375` w/o mTLS equates to exposing shell access to anybody on the network.
Please use `DOCKER_HOST=ssh://USER@HOST`, or configure mTLS.

https://docs.docker.com/engine/security/protect-access/
