### ISSUE TITLE
Failing to install rootless docker with non-root installed uidmap

### ISSUE THREAD

**Issue by maxswjeon** [rootless-containers/rootlesskit#326]
I am trying to install docker rootlessly. We don't have package `uidmap` installed to the system, so I installed it in `$HOME/.local` by compiling it by myself.

The compile process was executed like this
```bash
mkdir -p $HOME/.local/src
cd $HOME/.local/src
wget http://archive.ubuntu.com/ubuntu/pool/main/s/shadow/shadow_4.8.1.orig.tar.xz
tar xf shadow_4.8.1.orig.tar.xz
cd shadow_4.8.1
./configure --prefix=$HOME/.local
make -j
make install
```

After installing the shadow (uidmap), I logged out and logged back in to get the `$PATH` set right. (You can source the `$HOME/.profile` too)

The rootlesskit failes with this error
```
Sep 27 14:44:14 ubuntu-server dockerd-rootless.sh[3117122]: + exec rootlesskit --net=slirp4netns --mtu=65520 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run --propagation=rslave /home/rldocker/bin/dockerd-rootless.sh
Sep 27 14:44:14 ubuntu-server dockerd-rootless.sh[3117122]: [rootlesskit:parent] error: failed to setup UID/GID map: newuidmap 3117138 [0 1002 1 1 231072 65536] failed: newuidmap: write to uid_map failed: Operation not permitted
Sep 27 14:44:14 ubuntu-server dockerd-rootless.sh[3117122]: : exit status 1
```

If I install `uidmap` by the package (where I have root access), it works as a charm.

Is it a limitation or am I doing something wrong?

**Comment by maxswjeon** [comment]
So I found out that the [newuidmap and newgidmap should have setuid bit set and owned by root](https://unix.stackexchange.com/questions/692177/echo-to-gid-map-fails-but-uid-map-success) which is not the case in my problem. So there is no way to install docker without any help of sysadmins?

**Comment by AkihiroSuda** [comment]
> So there is no way to install docker without any help of sysadmins?

Right, for rootless Docker.

But you may still have a chance to create a VM and install Docker there if you are allowed to use `/dev/kvm`
