### ISSUE TITLE
pasta: support UDP forwarding

### ISSUE THREAD

**Issue by AkihiroSuda** [rootless-containers/rootlesskit#383]
UDP forwarding is not supported yet because pasta doesn't support periodically scanning UDP ports

**Comment by sbrivio-rh** [comment]
See also https://bugs.passt.top/show_bug.cgi?id=45. But nevertheless, we're working on support for explicit port forwarding configuration at runtime -- see also https://github.com/rootless-containers/rootlesskit/pull/358#issuecomment-1488583384.

**Comment by AkihiroSuda** [comment]
https://bugs.passt.top/show_bug.cgi?id=45

> Draft patch

Do you plan to merge this patch soon?

**Comment by sbrivio-rh** [comment]
> https://bugs.passt.top/show_bug.cgi?id=45
> 
> > Draft patch
> 
> Do you plan to merge this patch soon?

Sorry, the runtime port forwarding configuration got substantially delayed due to personal circumstances -- and I thought this patch wouldn't really help anybody.

But if it's useful for the moment for rootlesskit as a stopgap I can review, test (it's pratically untested), and merge it next week. I'll keep you posted.

**Comment by sbrivio-rh** [comment]
> But if it's useful for the moment for rootlesskit as a stopgap I can review, test (it's pratically untested), and merge it next week. I'll keep you posted.

It's a bit more complicated than that unfortunately: that patch works properly for loopback addresses, but it doesn't select the correct bound sockets for non-loopback addresses. I still need to adjust it a bit. I'm on it though.

**Comment by sbrivio-rh** [comment]
@AkihiroSuda this was finally implemented by @dgibson who reworked that implementation into something more manageable. Sorry for the delay.

The feature is available in passt version [2023_11_19.4f1709d](https://passt.top/passt/tag/?h=2023_11_19.4f1709d), as well as Fedora's [passt-0^20231119.g4f1709d-1.fc39](https://bodhi.fedoraproject.org/updates/FEDORA-2023-21025e43ac) and [passt-0^20231119.g4f1709d-1.fc40](https://bodhi.fedoraproject.org/updates/FEDORA-2023-eae3892288).

I still have to prepare a Debian package update, but, if it helps, unofficial [static build packages](https://passt.top/builds/latest/x86_64/) for x86_64 are available as usual.

**Comment by AkihiroSuda** [comment]
Thank you, will try 👍

**Comment by AkihiroSuda** [comment]
UDP forwarding still doesn't seem to work:

```console
$ pasta --version
pasta 2023_11_19.4f1709d
Copyright Red Hat
GNU General Public License, version 2 or later
  <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ pasta --tcp-ports=auto --udp-ports=auto -- iperf3 -s
No external routable interface for IPv6
-----------------------------------------------------------
Server listening on 5201 (test #1)
-----------------------------------------------------------
```

```console
$ iperf3 -c 127.0.0.1 -t 1
Connecting to host 127.0.0.1, port 5201
[  5] local 127.0.0.1 port 46322 connected to 127.0.0.1 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  4.97 GBytes  42.7 Gbits/sec    0   6.37 MBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-1.00   sec  4.97 GBytes  42.7 Gbits/sec    0             sender
[  5]   0.00-1.04   sec  4.97 GBytes  41.0 Gbits/sec                  receiver

iperf Done.
$ iperf3 -c 127.0.0.1 -t 1 -u
Connecting to host 127.0.0.1, port 5201
iperf3: error - unable to read from stream socket: Connection refused
```

**Comment by dgibson** [comment]
@AkihiroSuda, what's really weird here is that it's connecting fine once, but not again.

I note that you don't have `--config-net` on your pasta command line, which means the network won't be configured - so I wouldn't expect the command line as give to work.  But then, I'm not sure how it's seeming to connect once.

**Comment by dgibson** [comment]
@AkihiroSuda .  Sorry, I missed that your first run was TCP, but the second was UDP.  I can reproduce the problem once I do that correctly.

Looking closer it appears that the iperf3 client is doing a `recvfrom()` on the UDP socket without sending data first.  That's what's returning the `ECONNREFUSED`.  I'm not even sure what `ECONNREFUSED` on a UDP `recvfrom()` is supposed to mean :/.

**Comment by dgibson** [comment]
Sorry, I missed a step, the iperf3 client is sending a packet on the socket (with `write()` rather than `send()` surprisingly), which is getting an ICMP port unreachable.  I guess the `ECONNREFUSED` on the next `recvfrom()` is reporting that.

Note that the situation is more complex than it immediately seems here.  The iperf3 server only listens on TCP initially.  Only after it gets information on its TCP control connection does it open the UDP socket.  The client is attempting to use it very quickly after that, so there isn't time for `pasta` to observe the opened UDP socket and forward it.

However, `pasta` has handling more or less specifically for this situation: if a TCP port is listening we forward UDP as well.  I'm not sure why that's not working in this case.

**Comment by AkihiroSuda** [comment]
@dgibson Thank you for taking a look!

> I note that you don't have --config-net on your pasta command line, which means the network won't be configured - so I wouldn't expect the command line as give to work. 

Looks like `127.0.0.1` is still brought up even without `--config-net`.
I also confirmed `pasta --tcp-ports=5201 --udp-ports=5201 -- iperf3 -s`  just works.

>  I missed that your first run was TCP, but the second was UDP. 

Yes, I should have clarified this, sorry.

> Sorry, I missed a step, the iperf3 client is sending a packet on the socket (with write() rather than send() surprisingly), which is getting an ICMP port unreachable. I guess the ECONNREFUSED on the next recvfrom() is reporting that.

Not sure how ICMP is relevant here 🤔 

> Note that the situation is more complex than it immediately seems here. The iperf3 server only listens on TCP initially. Only after it gets information on its TCP control connection does it open the UDP socket. The client is attempting to use it very quickly after that, so there isn't time for pasta to observe the opened UDP socket and forward it.

Yes, iperf3 behaves kinda weird for UDP...

> However, pasta has handling more or less specifically for this situation: if a TCP port is listening we forward UDP as well. I'm not sure why that's not working in this case.

How is this implemented? Couldn't find the corresponding code.

**Comment by sbrivio-rh** [comment]
> @dgibson Thank you for taking a look!
> 
> > I note that you don't have --config-net on your pasta command line, which means the network won't be configured - so I wouldn't expect the command line as give to work.
> 
> Looks like `127.0.0.1` is still brought up even without `--config-net`. I also confirmed `pasta --tcp-ports=5201 --udp-ports=5201 -- iperf3 -s` just works.

Right, yes, for local connections we don't even need to set up a network interface, and we bring up `lo` in any case.

> > I missed that your first run was TCP, but the second was UDP.
> 
> Yes, I should have clarified this, sorry.
> 
> > Sorry, I missed a step, the iperf3 client is sending a packet on the socket (with write() rather than send() surprisingly), which is getting an ICMP port unreachable. I guess the ECONNREFUSED on the next recvfrom() is reporting that.
> 
> Not sure how ICMP is relevant here 🤔

The ICMP port unreachable is generated because we fail to bind the corresponding UDP ports, and Linux delivers that to applications as ECONNREFUSED on the next socket operation.

> > Note that the situation is more complex than it immediately seems here. The iperf3 server only listens on TCP initially. Only after it gets information on its TCP control connection does it open the UDP socket. The client is attempting to use it very quickly after that, so there isn't time for pasta to observe the opened UDP socket and forward it.
> 
> Yes, iperf3 behaves kinda weird for UDP...

So, meanwhile we found the issue (David had a hypothesis, which appears to be correct). Patch with thorough description at: https://archives.passt.top/passt-dev/20231121165426.1281012-1-sbrivio@redhat.com/

With this, iperf3 works for me as well:

```
$ ./pasta -- iperf3 -s1
-----------------------------------------------------------
Server listening on 5201 (test #1)
-----------------------------------------------------------
Accepted connection from ::1, port 44710
[  5] local ::1 port 5201 connected to ::1 port 60996
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-1.00   sec  2.98 GBytes  25.6 Gbits/sec  0.004 ms  48261/145977 (33%)  
[  5]   1.00-2.00   sec  3.31 GBytes  28.4 Gbits/sec  0.001 ms  40150/148625 (27%)  
[  5]   2.00-3.00   sec  3.50 GBytes  30.1 Gbits/sec  0.004 ms  41737/156489 (27%)  
[  5]   3.00-3.04   sec   144 MBytes  28.0 Gbits/sec  0.005 ms  1989/6609 (30%)  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-3.04   sec  9.94 GBytes  28.0 Gbits/sec  0.005 ms  132137/457700 (29%)  receiver
```

```
$ iperf3 -c ::1 -u -t 3 -b 40G
Connecting to host ::1, port 5201
[  5] local ::1 port 60996 connected to ::1 port 5201
[ ID] Interval           Transfer     Bitrate         Total Datagrams
[  5]   0.00-1.00   sec  4.66 GBytes  40.0 Gbits/sec  152569  
[  5]   1.00-2.00   sec  4.53 GBytes  38.9 Gbits/sec  148302  
[  5]   2.00-3.00   sec  4.79 GBytes  41.1 Gbits/sec  156834  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-3.00   sec  14.0 GBytes  40.0 Gbits/sec  0.000 ms  0/457705 (0%)  sender
[  5]   0.00-3.04   sec  9.94 GBytes  28.0 Gbits/sec  0.005 ms  132137/457700 (29%)  receiver
```

> > However, pasta has handling more or less specifically for this situation: if a TCP port is listening we forward UDP as well. I'm not sure why that's not working in this case.
> 
> How is this implemented? Couldn't find the corresponding code.

There you go: https://passt.top/passt/tree/port_fwd.c?id=4f1709db1b61c14729a6313d860323ec65772a37#n85

...let me know if you would like a quick build/package to test this.

**Comment by AkihiroSuda** [comment]
> So, meanwhile we found the issue (David had a hypothesis, which appears to be correct). Patch with thorough description at: https://archives.passt.top/passt-dev/20231121165426.1281012-1-sbrivio@redhat.com/

Thanks, will trigger the CI
- https://github.com/rootless-containers/rootlesskit/pull/403

**Comment by AkihiroSuda** [comment]
Couldn't compile
```console
$ git log --oneline HEAD~2...HEAD
a2c1806 (HEAD -> master) port_fwd, util: Don't bind UDP ports with opposite-side bound TCP ports
4f1709d (tag: 2023_11_19.4f1709d, origin/master, origin/HEAD, mirror/master) valgrind: Don't disable optimizations for valgrind builds

$ make
seccomp profile passt allows:  accept4 bind clock_gettime close connect
   epoll_ctl epoll_pwait epoll_wait exit_group fallocate fcntl ftruncate
   getsockopt listen lseek read recvfrom recvmmsg recvmsg sendmmsg sendmsg
   sendto setsockopt shutdown socket timerfd_create timerfd_gettime
   timerfd_settime write writev
seccomp profile pasta allows:  accept4 bind clock_gettime clone close
   connect epoll_ctl epoll_pwait epoll_wait exit exit_group fallocate
   fcntl ftruncate getsockname getsockopt ioctl listen lseek openat pipe2
   read recvfrom recvmmsg recvmsg rt_sigprocmask rt_sigreturn sendmmsg
   sendmsg sendto setns setsockopt shutdown socket splice timerfd_create
   timerfd_gettime timerfd_settime waitid write writev
cc -Wall -Wextra -Wno-format-zero-length -pedantic -std=c11 -D_XOPEN_SOURCE=700 -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -O2 -pie -fPIE -DPAGE_SIZE=4096 -DNETNS_RUN_DIR=\"/run/netns\" -DPASST_AUDIT_ARCH=AUDIT_ARCH_X86_64 -DRLIMIT_STACK_VAL=8192 -DARCH=\"x86_64\" -DVERSION=\"2023_11_19.4f1709d-1-ga2c1806\" -DDUAL_STACK_SOCKETS=1 -DHAS_SND_WND -DHAS_BYTES_ACKED -DHAS_MIN_RTT -DHAS_GETRANDOM -fstack-protector-strong   arch.c arp.c checksum.c conf.c dhcp.c dhcpv6.c icmp.c igmp.c isolation.c lineread.c log.c mld.c ndp.c netlink.c packet.c passt.c pasta.c pcap.c port_fwd.c tap.c tcp.c tcp_splice.c udp.c util.c -o passt 
udp.c: In function ‘udp_timer’:
udp.c:1262:25: error: too few arguments to function ‘port_fwd_scan_udp’
 1262 |                         port_fwd_scan_udp(&c->udp.fwd_out.f, &c->udp.fwd_in.f,
      |                         ^~~~~~~~~~~~~~~~~
In file included from passt.h:41,
                 from udp.c:115:
port_fwd.h:39:6: note: declared here
   39 | void port_fwd_scan_udp(struct port_fwd *fwd, const struct port_fwd *rev,
      |      ^~~~~~~~~~~~~~~~~
udp.c:1268:25: error: too few arguments to function ‘port_fwd_scan_udp’
 1268 |                         port_fwd_scan_udp(&c->udp.fwd_in.f, &c->udp.fwd_out.f,
      |                         ^~~~~~~~~~~~~~~~~
port_fwd.h:39:6: note: declared here
   39 | void port_fwd_scan_udp(struct port_fwd *fwd, const struct port_fwd *rev,
      |      ^~~~~~~~~~~~~~~~~
make: *** [Makefile:113: passt] Error 1
```

**Comment by sbrivio-rh** [comment]
Gah, sorry, I just realised -- I left out some changes from the commit. New patch coming.

**Comment by sbrivio-rh** [comment]
Fixed patch at https://archives.passt.top/passt-dev/20231121180152.1364915-1-sbrivio@redhat.com/

**Comment by AkihiroSuda** [comment]
Thanks, the CI now passes
- #403

**Comment by AkihiroSuda** [comment]
BTW, for supporting (kernel-mode) VXLAN, we still need an explicit API (https://github.com/rootless-containers/rootlesskit/pull/358#issuecomment-1488583384) to reconfigure the port forwards, as the UDP ports used by the kernel do not show up in procfs.

**Comment by sbrivio-rh** [comment]
Sure, that's known, @dgibson is working on it (actually, in a more generic way than https://github.com/rootless-containers/rootlesskit/pull/358#issuecomment-1488583384)

**Comment by AkihiroSuda** [comment]
> Sure, that's known, @dgibson is working on it (actually, in a more generic way than [#358 (comment)](https://github.com/rootless-containers/rootlesskit/pull/358#issuecomment-1488583384))

Thanks, is there any WIP git branch that I can watch?

**Comment by sbrivio-rh** [comment]
> > Sure, that's known, @dgibson is working on it (actually, in a more generic way than [#358 (comment)](https://github.com/rootless-containers/rootlesskit/pull/358#issuecomment-1488583384))
> 
> Thanks, is there any WIP git branch that I can watch?

No, sorry, not yet... but it started like [this](https://archives.passt.top/passt-dev/20231130020222.4056647-1-david@gibson.dropbear.id.au/) :)

**Comment by dgibson** [comment]
> > > Sure, that's known, @dgibson is working on it (actually, in a more generic way than [#358 (comment)](https://github.com/rootless-containers/rootlesskit/pull/358#issuecomment-1488583384))
> > 
> > 
> > Thanks, is there any WIP git branch that I can watch?
> 
> No, sorry, not yet... but it started like [this](https://archives.passt.top/passt-dev/20231130020222.4056647-1-david@gibson.dropbear.id.au/) :)

Yeah, I'm afraid it's currently a shifting bundle of branches that I'm shuffling and rebasing sometimes multiple times a day.  Although I've done a lot of work, for now it's mostly preliminaries and mechanics, it doesn't really do anything new yet, so there wouldn't be much value in trying it out anyway.
