### ISSUE TITLE
Unable to access registry on SSH port-forwarded localhost even with host-loopback enabled

### ISSUE THREAD

**Issue by BrianHVB** [rootless-containers/rootlesskit#398]
We have a private container registry hosted on a server. For security, the repository only listens to connections on localhost. To access it from the local network we SSH to the server, forwarding port 5000 (`ssh -L 5000:localhost:5000 remote-server`). 

We then treat the private repository as if it were running on the host

```
docker pull localhost:5000/my_repository:latest
docker push localhost:5000/my_other_respository:v2.0
```
Within a `rootlesskit` context, these commands are not able to access the local private registry. I have tried several workarounds and made partial progress, but still can't get `docker pull/push` to access the local registry.

Here is an MVP

```
# add localhost:5000 to the insecure registries
nano  ~/.config/docker/daemon.json
systemctl --user restart docker

# make sure to start rootlesskit with host-loopback enabled
rootlesskit --copy-up=/etc --net=slirp4netns bash

# confirm that the registry is up and accessible via slirp's gateway address for the interface
curl http://10.0.2.2:5000/v2/_catalog
# > {"repositories":[]}

# create a tag
docker pull hello-world
docker tag hello-world 10.0.2.2:5000/test_repo

# confirm 10.0.2.2 is marked insecure
docker info | grep -A 5 "Insecure"

# try and push
docker push 10.0.2.2:5000/test_repo
# > Using default tag: latest
# > The push refers to repository [10.0.2.2:5000/test_repo]
# > Get "http://10.0.2.2:5000/v2/": dial tcp 10.0.2.2:5000: connect: network is unreachable

# try with localhost
curl http://localhost:5000/v2/_catalog
# > curl: (7) Failed to connect to localhost port 5000: Connection refused
```

I tried a different variation where I created the SSH forwarding inside the rootlesskit namespace, but had the same result: curl commands worked, but `docker push` did not.

```
rootlesskit --copy-up=/etc --net=slirp4netns bash
ssh -fN -L 5000:localhost:5000 user@remote_machine

curl http://localhost:5000/v2/_catalog
# > {"repositories":[""]}

docker push localhost:5000/test_repo
# > Using default tag: latest
# > The push refers to repository [localhost:5000/test_repo]
# > Get "http://localhost:5000/v2/": dial tcp [::1]:5000: connect: connection refused
```

The --user docker logs don't show anything useful
```
Nov 01 13:55:25 ... dockerd-rootless.sh[11594]: time="..." level=info msg="Attempting next endpoint for push after error: Get \"https://localhost:5000/v2/\": dial tcp [::1]:5000: connect: connection refused"
Nov 01 13:55:25 ... dockerd-rootless.sh[11594]: time="..." level=info msg="Attempting next endpoint for push after error: Get \"http://localhost:5000/v2/\": dial tcp [::1]:5000: connect: connection refused"

```
I've also tried using `--net=host` but had the same results.

Something in`rootlesskit` or the interaction between `docker` and `rootlesskit` is preventing network requests from going through.

Is there some configuration that will allow docker to push/pull to a "local" private registry exposed through SSH?

**Comment by AkihiroSuda** [comment]
Duplicate of
- https://github.com/docker/cli/issues/4634
