### ISSUE TITLE
DinD Rootless does not work on macOS: Daemon not found

### ISSUE THREAD

**Issue by Playjasb2** [rootless-containers/rootlesskit#418]
**Issue:**

When attempting run rootless DinD on macOS, the container is unable to spawn Docker containers inside it because it is unable to connect to the Docker Daemon.

**Expected Result:**

The DinD container should be able to spawn new containers inside it without issue. Docker and Docker-Compose should work without fail.

**Config:**
- M1 Max Macbook Pro
- Docker Desktop v4.27.1
- Docker Engine v25.0.2

**Steps to Reproduce Issue:**
1. Have the setup above.
2. Execute: `docker run --privileged --name some-docker-test -d \
        docker:dind-rootless --experimental`
3. Execute the following to get inside the container: `docker exec -it <container hash from step 2> sh`
4. Execute `docker info` and notice the message: `ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

**Comment by AkihiroSuda** [comment]
Is this issue specific to Docker for Mac? If not, please do not include "does not work on macos" in the issue title

**Comment by AkihiroSuda** [comment]
You have to set `DOCKER_HOST` explicitly
```
DOCKER_HOST=unix:///run/user/1000/docker.sock docker info
```

**Comment by AkihiroSuda** [comment]
FYI, there was a PR to set `DOCKER_HOST` by default, but it was rejected:
- https://github.com/docker-library/docker/pull/266
