### ISSUE TITLE
vpnkit performance

### ISSUE THREAD

**Issue by tonistiigi** [rootless-containers/rootlesskit#6]
I tried to measure network speed when using vpnkit with rootlesskit. One thing I noticed was that the upload speed was very low by default, like 200x lower than expected. After tweaking https://github.com/AkihiroSuda/rootlesskit/blob/c166fc61352542ac0423b5abe84d00450f2b7197/pkg/child/child.go#L154 I could make it much more performant and actually faster than the download speed. I'm not sure how reproducible that is and what the correct value should be so didn't make a PR yet. Trying different values from 1500 to 32K it appeared to max somewhere around the middle for me but my measurement method wasn't very precise.

There may be some other things to try with a better benchmark. With the tweaks, it still was ~1.5-2x slower than baseline in my case. And slower than Docker for Mac that also uses vpnkit (although a different os).

**Comment by AkihiroSuda** [comment]
Thanks!
Could you also try vdeplug slirp?

**Comment by AkihiroSuda** [comment]
Probably setting the buffer size to 65536 does not hurt?

@djs55 PTAL?

**Comment by djs55** [comment]
200x sounds very bad -- could there be an issue with the MTU? I think the default MTU is set to 1500 bytes which excludes the ethernet header, so the buffer needs to be a bit larger than 1500 to avoid truncating ethernet frames (which probably manifests as unexpected packet loss interpreted as congestion, causing backoff)
 
I think there's no harm in making this buffer 65536. In the future we might want to increase the default MTU anyway, so this would help. Unfortunately there's a known bug in the TCP stack triggered by increasing the MTU -- see https://github.com/mirage/mirage-tcpip/pull/309

I wonder if it would make sense to make `vpnkit` open the tap device itself and `read`/`write` directly to avoid the copy through the Unix domain socket. What do you think?

**Comment by AkihiroSuda** [comment]
Thanks @djs55 :+1:


@tonistiigi Could you provide your benchmark script?

**Comment by AkihiroSuda** [comment]
> I wonder if it would make sense to make vpnkit open the tap device itself and read/write directly to avoid the copy through the Unix domain socket. What do you think?

We need the slirp stack in the parent namespace and the tap stack in the child user+net+mount namespace, but I'm not sure how we can connect them without using socket/pipe and forking, because multi-threaded program cannot enter the child user+net+mount namespace.

I tried whether we can access `/proc/CHILD/root/dev/net/tun` from the parent, but it failed with EPERM (as I expected).

cc @cyphar Any thought?

**Comment by AkihiroSuda** [comment]
Oh, I confirmed we can send tapfd from the child to the parent as `SCM_RIGHTS` msg :smiley:

**Comment by AkihiroSuda** [comment]
@djs55 Is it possible to implement the SCM_RIGHTS technique for VPNKit?
OCaml does not seem to support calling setns(2)?
