### ISSUE TITLE
failed to start the child: fork/exec /proc/self/exe: permission denied

### ISSUE THREAD

**Issue by lightyou** [rootless-containers/rootlesskit#68]
I try using dockerd-rootless on a rancher cluster as for building docker images for CI/CD.
I use a Jenkins slave image as a base image (jenkins/jnlp-slave:3.27-1) where I installed docker rootless from https://get.docker.com/rootless.

When executing rootlesskit I have the following error :
```
$ rootlesskit sh
[rootlesskit:parent] error: failed to start the child: fork/exec /proc/self/exe: permission denied
$ rootlesskit -v
rootlesskit version 0.4.1
```

**Comment by AkihiroSuda** [comment]
You need --privileged or at least seccomp=unconfined apparmor=unconfined systempaths=unconfined

**Comment by AkihiroSuda** [comment]
For building images I suggest using rootless BuildKit rather than rootless Docker. You still need seccomp=unconfined (anyway unconfined by default on kube) apparmpr=unconfined but you dont need systempaths=unconfined.

**Comment by zhenhua** [comment]
@AkihiroSuda I meet the same problem when try to run /home/moby/bin/dockerd-rootless.sh. It fails to start the docker daemon with following errors:

[moby@eci-dev bin]$ /home/moby/bin/dockerd-rootless.sh --experimental --storage-driver vfs
+ '[' -w /tmp/docker-1000 ']'
+ '[' -w /home/moby ']'
+ rootlesskit=
+ for f in docker-rootlesskit rootlesskit
+ which docker-rootlesskit
+ for f in docker-rootlesskit rootlesskit
+ which rootlesskit
+ rootlesskit=rootlesskit
+ break
+ '[' -z rootlesskit ']'
+ : ''
+ : ''
+ net=
+ mtu=
+ '[' -z ']'
+ which slirp4netns
+ slirp4netns --help
+ grep -- --disable-host-loopback
--disable-host-loopback  prohibit connecting to 127.0.0.1:* on the host namespace
+ net=slirp4netns
+ '[' -z ']'
+ mtu=65520
+ '[' -z slirp4netns ']'
+ '[' -z 65520 ']'
+ '[' -z ']'
+ _DOCKERD_ROOTLESS_CHILD=1
+ export _DOCKERD_ROOTLESS_CHILD
+ exec rootlesskit --net=slirp4netns --mtu=65520 --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run /home/moby/bin/dockerd-rootless.sh --experimental --storage-driver vfs
WARN[0000] "builtin" port driver is experimental
[rootlesskit:parent] error: failed to start the child: fork/exec /proc/self/exe: invalid argument

any ideas?

**Comment by zhenhua** [comment]
@lightyou I meet the same issue and the root cause is that the kernel needs to update on my CentOS 7.3. You need to make sure that kernel has the user namespace. I update my kernel from  3.10.0-514.26.2.el7.x86_64  to 3.10.0-957.21.2.el7, then it works for me.

**Comment by AkihiroSuda** [comment]
closable?
