### ISSUE TITLE
Specify lxc config

### ISSUE THREAD

**Issue by Rajczyk** [rootless-containers/rootlesskit#71]
I'm playing around with rootless docker and lxc, and It was working well. I wanted to attach the create LXC veth pair to my Open vSwitch. However it is difficult to work out which device has been connected to each "namespace".  
 
I have not made any code changes to rootlesskit yet, but I was wondering if its just simply setting the following line to a real place https://github.com/rootless-containers/rootlesskit/blob/0359c83c4422b7c4c8696826649d1c8ec22437d9/pkg/network/lxcusernic/lxcusernic.go#L51

which as ~/.lxc/config and including the following config?
```
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = lxcbr0
lxc.network.hwaddr = 00:16:3e:fe:d7:f0
lxc.network.name = veth0
lxc.network.veth.pair = veth-<a know name>
```

Or is there a more important reason this path is set to /dev/null? 
Or is there a better way to control the host veth name?

Thanks for any input.

**Comment by AkihiroSuda** [comment]
http://man7.org/linux/man-pages/man1/lxc-user-nic.1.html

>  lxcpath
>              The path of the container. This is currently not used.

**Comment by Rajczyk** [comment]
you are correct, passing a lxcpath makes no difference. I have played around trying to get it to load a config file from a global / home directory. However, nothing seems to work.
