### ISSUE TITLE
Running all containers with a single privileged user

### ISSUE THREAD

**Issue by hashtagkarma** [rootless-containers/rootlesskit#79]
From https://github.com/containers/libpod/blob/master/README.md

>Rootless Podman runs locked-down containers with no privileges that the user running the container does not have. Some of these restrictions can be lifted (via --privileged, for example), but **rootless containers will never have more privileges than the user that launched them**.

I assume the same is true for rootless Docker. 

With that in mind, **would it be a bad idea to run all your services inside containers using the root user**? Maybe _Single-mapping mode_ considered that. The problems I'm facing are mostly related to volume and folder permissions/IDs between host and containers. And the requirements of builds and each service of course.

It's not possible to make a non-root ID match e.g. 1000:1000 from the host because

> Inside rootlesskit, your UID is mapped to 0 but it is not the real root

and the volumes are owned by root.

**Comment by AkihiroSuda** [comment]
Sorry, couldn't get what you mean.

>  would it be a bad idea to run all your services inside containers using the root user?

You meant using a single non-root user?

**Comment by hashtagkarma** [comment]
No, using only the _root_ user since the mapping is done automatically since AFAIK you can't map both root and non-root to your host IDs outside the container. On non-rootless Docker that's how many people solved their volume and other permission issues, by mapping _www-data_ and etc to their host IDs. It was the easiest and most straighforward way to solve those issues.
The hypothetical setup below is **not** possible with rootless docker:

- Outside the container:
  - Your user UID/GID is 1000:1000
  - Folders owned by 1000:1000
- Inside the container:
  - The root user is 0:0 and not mapped automatically
  - You recreate a user/group like _www-data_ with 1000:1000 IDs and map them to your external IDs
  - Volumes and folders are owned by 1000:1000
  - Dockerfiles with `USER root`
  - Services like _nginx_ run as `www-data`

So the fix would be to use root for everything inside the container:
- _nginx.conf_ with `user root`;
- _php-fpm_ with `--allow-to-run-as-root` and `user = root` \ `group = root`
- Rootlesskit already mapped that user to your IDs so there are no permission problems
